import{a as g,S as h,i as n}from"./assets/vendor-C3hA4BqS.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();const L="55520229-6b38dd18315a985816c1e4a23",b="https://pixabay.com/api/",u=15;async function w(e,s=1){const{data:t}=await g(b,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:u,page:s}});return t.total_pages=Math.ceil(t.totalHits/u),t}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".btn-load-more"),S=new h(".gallery-thumb",{captionDelay:1e3,captionsData:"alt"});function v(e){const s=e.map(t=>`
          <li class="gallery-item">
          <a class="gallery-thumb" href="${t.largeImageURL}"><img class="gallery-img" src="${t.webformatURL}" alt="${t.name||t.tags}" /></a>
          <ul class="gallery-content-list">
            <li class="gallery-content-item"><span>Likes</span><span>${t.likes}</span></li>
            <li class="gallery-content-item"><span>Views</span><span>${t.views}</span></li>
            <li class="gallery-content-item"><span>Comments</span><span>${t.comments}</span></li>
            <li class="gallery-content-item"><span>Downloads</span><span>${t.downloads}</span></li>
          </ul>
      </li>`).join("");p.insertAdjacentHTML("beforeend",s),S.refresh()}function M(){p.innerHTML=""}function q(){m.classList.remove("is-hidden")}function $(){m.classList.add("is-hidden")}function B(){y.classList.remove("is-hidden")}function O(){y.classList.add("is-hidden")}const P=document.querySelector(".form"),d=document.querySelector(".gallery"),A=document.querySelector(".btn-load-more");let i="",a=1;n.settings({pauseOnHover:!0,position:"topRight"});P.addEventListener("submit",E);A.addEventListener("click",R);async function E(e){e.preventDefault(),i=e.target.elements["search-text"].value.trim(),i!==""&&(M(),a=1,await f())}async function R(e){a+=1,await f(),_()}async function f(){q(),O();try{const e=await w(i,a);if(!e.hits.length){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}v(e.hits),a<e.total_pages?B():n.info({message:"We're sorry, but you've reached the end of search results."})}catch(e){n.error({message:e.message})}finally{$()}}function _(){const e=d.querySelector(".gallery-item"),s=parseInt(getComputedStyle(d).rowGap),t=(e==null?void 0:e.getBoundingClientRect().height)??0;scrollBy({top:Math.round((t+s)*2),behavior:"smooth"})}
//# sourceMappingURL=index.js.map
